sudo: false
dist: trusty
language: node_js

node_js:
  - 8

env:
  global:
    - NODE_ENV=production

branches:
  only:
    - master
    - beta

notifications:
  email: false

# Ensure node and npm major version matches from package.json
before_install:
  - nvm install "$(jq -r '.engines.node' package.json | egrep -oe "[0-9]+" | head -n1)"
  - npm i -g npm@$(jq -r '.engines.npm' package.json | egrep -oe "[0-9]+" | head -n1)

install:
  - npm ci

cache:
  directories:
    - "$HOME/.npm"

script:
    - npm run build
    - sleep 10 # Give server enough time to spin up

# Disabling sanity test curl test until REACT_APP_WPAPI_ROOT is ready
#    - curl -s --fail "http://localhost:3001" > /dev/null